// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="convolve_fpga_convolve_fpga,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu200-fsgd2104-2-e,HLS_INPUT_CLOCK=2.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=1.460000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=18,HLS_SYN_DSP=0,HLS_SYN_FF=6178,HLS_SYN_LUT=6410,HLS_VERSION=2020_1}" *)

module convolve_fpga (
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        ap_clk,
        ap_rst_n,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        m_axi_gmem3_AWVALID,
        m_axi_gmem3_AWREADY,
        m_axi_gmem3_AWADDR,
        m_axi_gmem3_AWID,
        m_axi_gmem3_AWLEN,
        m_axi_gmem3_AWSIZE,
        m_axi_gmem3_AWBURST,
        m_axi_gmem3_AWLOCK,
        m_axi_gmem3_AWCACHE,
        m_axi_gmem3_AWPROT,
        m_axi_gmem3_AWQOS,
        m_axi_gmem3_AWREGION,
        m_axi_gmem3_AWUSER,
        m_axi_gmem3_WVALID,
        m_axi_gmem3_WREADY,
        m_axi_gmem3_WDATA,
        m_axi_gmem3_WSTRB,
        m_axi_gmem3_WLAST,
        m_axi_gmem3_WID,
        m_axi_gmem3_WUSER,
        m_axi_gmem3_ARVALID,
        m_axi_gmem3_ARREADY,
        m_axi_gmem3_ARADDR,
        m_axi_gmem3_ARID,
        m_axi_gmem3_ARLEN,
        m_axi_gmem3_ARSIZE,
        m_axi_gmem3_ARBURST,
        m_axi_gmem3_ARLOCK,
        m_axi_gmem3_ARCACHE,
        m_axi_gmem3_ARPROT,
        m_axi_gmem3_ARQOS,
        m_axi_gmem3_ARREGION,
        m_axi_gmem3_ARUSER,
        m_axi_gmem3_RVALID,
        m_axi_gmem3_RREADY,
        m_axi_gmem3_RDATA,
        m_axi_gmem3_RLAST,
        m_axi_gmem3_RID,
        m_axi_gmem3_RUSER,
        m_axi_gmem3_RRESP,
        m_axi_gmem3_BVALID,
        m_axi_gmem3_BREADY,
        m_axi_gmem3_BRESP,
        m_axi_gmem3_BID,
        m_axi_gmem3_BUSER,
        inFrame,
        outFrame,
        coefficient,
        coefficient_size,
        img_width,
        img_height,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);

parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM3_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM3_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM3_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM3_USER_VALUE = 0;
parameter    C_M_AXI_GMEM3_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM3_CACHE_VALUE = 3;

parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM3_WSTRB_WIDTH = (32 / 8);

output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
output   m_axi_gmem3_AWVALID;
input   m_axi_gmem3_AWREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_AWADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_AWID;
output  [7:0] m_axi_gmem3_AWLEN;
output  [2:0] m_axi_gmem3_AWSIZE;
output  [1:0] m_axi_gmem3_AWBURST;
output  [1:0] m_axi_gmem3_AWLOCK;
output  [3:0] m_axi_gmem3_AWCACHE;
output  [2:0] m_axi_gmem3_AWPROT;
output  [3:0] m_axi_gmem3_AWQOS;
output  [3:0] m_axi_gmem3_AWREGION;
output  [C_M_AXI_GMEM3_AWUSER_WIDTH - 1:0] m_axi_gmem3_AWUSER;
output   m_axi_gmem3_WVALID;
input   m_axi_gmem3_WREADY;
output  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_WDATA;
output  [C_M_AXI_GMEM3_WSTRB_WIDTH - 1:0] m_axi_gmem3_WSTRB;
output   m_axi_gmem3_WLAST;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_WID;
output  [C_M_AXI_GMEM3_WUSER_WIDTH - 1:0] m_axi_gmem3_WUSER;
output   m_axi_gmem3_ARVALID;
input   m_axi_gmem3_ARREADY;
output  [C_M_AXI_GMEM3_ADDR_WIDTH - 1:0] m_axi_gmem3_ARADDR;
output  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_ARID;
output  [7:0] m_axi_gmem3_ARLEN;
output  [2:0] m_axi_gmem3_ARSIZE;
output  [1:0] m_axi_gmem3_ARBURST;
output  [1:0] m_axi_gmem3_ARLOCK;
output  [3:0] m_axi_gmem3_ARCACHE;
output  [2:0] m_axi_gmem3_ARPROT;
output  [3:0] m_axi_gmem3_ARQOS;
output  [3:0] m_axi_gmem3_ARREGION;
output  [C_M_AXI_GMEM3_ARUSER_WIDTH - 1:0] m_axi_gmem3_ARUSER;
input   m_axi_gmem3_RVALID;
output   m_axi_gmem3_RREADY;
input  [C_M_AXI_GMEM3_DATA_WIDTH - 1:0] m_axi_gmem3_RDATA;
input   m_axi_gmem3_RLAST;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_RID;
input  [C_M_AXI_GMEM3_RUSER_WIDTH - 1:0] m_axi_gmem3_RUSER;
input  [1:0] m_axi_gmem3_RRESP;
input   m_axi_gmem3_BVALID;
output   m_axi_gmem3_BREADY;
input  [1:0] m_axi_gmem3_BRESP;
input  [C_M_AXI_GMEM3_ID_WIDTH - 1:0] m_axi_gmem3_BID;
input  [C_M_AXI_GMEM3_BUSER_WIDTH - 1:0] m_axi_gmem3_BUSER;
input  [63:0] inFrame;
input  [63:0] outFrame;
input  [63:0] coefficient;
input  [31:0] coefficient_size;
input  [31:0] img_width;
input  [31:0] img_height;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [31:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
 reg    ap_rst_n_inv;
wire    gmem2_AWREADY;
wire    gmem2_WREADY;
wire    gmem2_ARREADY;
wire    gmem2_RVALID;
wire   [31:0] gmem2_RDATA;
wire    gmem2_RLAST;
wire   [0:0] gmem2_RID;
wire   [0:0] gmem2_RUSER;
wire   [1:0] gmem2_RRESP;
wire    gmem2_BVALID;
wire   [1:0] gmem2_BRESP;
wire   [0:0] gmem2_BID;
wire   [0:0] gmem2_BUSER;
wire    gmem3_AWREADY;
wire    gmem3_WREADY;
wire    gmem3_ARREADY;
wire    gmem3_RVALID;
wire   [31:0] gmem3_RDATA;
wire    gmem3_RLAST;
wire   [0:0] gmem3_RID;
wire   [0:0] gmem3_RUSER;
wire   [1:0] gmem3_RRESP;
wire    gmem3_BVALID;
wire   [1:0] gmem3_BRESP;
wire   [0:0] gmem3_BID;
wire   [0:0] gmem3_BUSER;
wire    Block_split1_proc9_U0_ap_start;
wire    Block_split1_proc9_U0_ap_done;
wire    Block_split1_proc9_U0_ap_continue;
wire    Block_split1_proc9_U0_ap_idle;
wire    Block_split1_proc9_U0_ap_ready;
wire    Block_split1_proc9_U0_start_out;
wire    Block_split1_proc9_U0_start_write;
wire   [31:0] Block_split1_proc9_U0_img_width_out_din;
wire    Block_split1_proc9_U0_img_width_out_write;
wire   [31:0] Block_split1_proc9_U0_elements_out_out_din;
wire    Block_split1_proc9_U0_elements_out_out_write;
wire   [63:0] Block_split1_proc9_U0_inFrame_out_din;
wire    Block_split1_proc9_U0_inFrame_out_write;
wire   [63:0] Block_split1_proc9_U0_outFrame_out_din;
wire    Block_split1_proc9_U0_outFrame_out_write;
wire   [63:0] Block_split1_proc9_U0_coefficient_out_din;
wire    Block_split1_proc9_U0_coefficient_out_write;
wire    read_dataflow_1_U0_ap_start;
wire    read_dataflow_1_U0_ap_done;
wire    read_dataflow_1_U0_ap_continue;
wire    read_dataflow_1_U0_ap_idle;
wire    read_dataflow_1_U0_ap_ready;
wire   [31:0] read_dataflow_1_U0_read_stream_din;
wire    read_dataflow_1_U0_read_stream_write;
wire    read_dataflow_1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] read_dataflow_1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_AWID;
wire   [31:0] read_dataflow_1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] read_dataflow_1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] read_dataflow_1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] read_dataflow_1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] read_dataflow_1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_AWUSER;
wire    read_dataflow_1_U0_m_axi_gmem1_WVALID;
wire   [31:0] read_dataflow_1_U0_m_axi_gmem1_WDATA;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_WSTRB;
wire    read_dataflow_1_U0_m_axi_gmem1_WLAST;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_WID;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_WUSER;
wire    read_dataflow_1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] read_dataflow_1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_ARID;
wire   [31:0] read_dataflow_1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] read_dataflow_1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] read_dataflow_1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] read_dataflow_1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] read_dataflow_1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] read_dataflow_1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] read_dataflow_1_U0_m_axi_gmem1_ARUSER;
wire    read_dataflow_1_U0_m_axi_gmem1_RREADY;
wire    read_dataflow_1_U0_m_axi_gmem1_BREADY;
wire    read_dataflow_1_U0_inFrame_read;
wire    read_dataflow_1_U0_img_width_read;
wire    read_dataflow_1_U0_elements_loc_read;
wire   [31:0] read_dataflow_1_U0_img_width_out_din;
wire    read_dataflow_1_U0_img_width_out_write;
wire   [31:0] read_dataflow_1_U0_elements_loc_out_din;
wire    read_dataflow_1_U0_elements_loc_out_write;
wire    compute_dataflow_1_U0_ap_start;
wire    compute_dataflow_1_U0_ap_done;
wire    compute_dataflow_1_U0_ap_continue;
wire    compute_dataflow_1_U0_ap_idle;
wire    compute_dataflow_1_U0_ap_ready;
wire   [31:0] compute_dataflow_1_U0_write_stream_din;
wire    compute_dataflow_1_U0_write_stream_write;
wire    compute_dataflow_1_U0_read_stream_read;
wire    compute_dataflow_1_U0_m_axi_gmem3_AWVALID;
wire   [63:0] compute_dataflow_1_U0_m_axi_gmem3_AWADDR;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_AWID;
wire   [31:0] compute_dataflow_1_U0_m_axi_gmem3_AWLEN;
wire   [2:0] compute_dataflow_1_U0_m_axi_gmem3_AWSIZE;
wire   [1:0] compute_dataflow_1_U0_m_axi_gmem3_AWBURST;
wire   [1:0] compute_dataflow_1_U0_m_axi_gmem3_AWLOCK;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_AWCACHE;
wire   [2:0] compute_dataflow_1_U0_m_axi_gmem3_AWPROT;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_AWQOS;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_AWREGION;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_AWUSER;
wire    compute_dataflow_1_U0_m_axi_gmem3_WVALID;
wire   [31:0] compute_dataflow_1_U0_m_axi_gmem3_WDATA;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_WSTRB;
wire    compute_dataflow_1_U0_m_axi_gmem3_WLAST;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_WID;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_WUSER;
wire    compute_dataflow_1_U0_m_axi_gmem3_ARVALID;
wire   [63:0] compute_dataflow_1_U0_m_axi_gmem3_ARADDR;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_ARID;
wire   [31:0] compute_dataflow_1_U0_m_axi_gmem3_ARLEN;
wire   [2:0] compute_dataflow_1_U0_m_axi_gmem3_ARSIZE;
wire   [1:0] compute_dataflow_1_U0_m_axi_gmem3_ARBURST;
wire   [1:0] compute_dataflow_1_U0_m_axi_gmem3_ARLOCK;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_ARCACHE;
wire   [2:0] compute_dataflow_1_U0_m_axi_gmem3_ARPROT;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_ARQOS;
wire   [3:0] compute_dataflow_1_U0_m_axi_gmem3_ARREGION;
wire   [0:0] compute_dataflow_1_U0_m_axi_gmem3_ARUSER;
wire    compute_dataflow_1_U0_m_axi_gmem3_RREADY;
wire    compute_dataflow_1_U0_m_axi_gmem3_BREADY;
wire    compute_dataflow_1_U0_coefficient_read;
wire    compute_dataflow_1_U0_img_width_read;
wire    compute_dataflow_1_U0_elements_loc_read;
wire   [31:0] compute_dataflow_1_U0_elements_loc_out_din;
wire    compute_dataflow_1_U0_elements_loc_out_write;
wire    write_dataflow_1_U0_ap_start;
wire    write_dataflow_1_U0_ap_done;
wire    write_dataflow_1_U0_ap_continue;
wire    write_dataflow_1_U0_ap_idle;
wire    write_dataflow_1_U0_ap_ready;
wire    write_dataflow_1_U0_m_axi_gmem2_AWVALID;
wire   [63:0] write_dataflow_1_U0_m_axi_gmem2_AWADDR;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_AWID;
wire   [31:0] write_dataflow_1_U0_m_axi_gmem2_AWLEN;
wire   [2:0] write_dataflow_1_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] write_dataflow_1_U0_m_axi_gmem2_AWBURST;
wire   [1:0] write_dataflow_1_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] write_dataflow_1_U0_m_axi_gmem2_AWPROT;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_AWQOS;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_AWREGION;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_AWUSER;
wire    write_dataflow_1_U0_m_axi_gmem2_WVALID;
wire   [31:0] write_dataflow_1_U0_m_axi_gmem2_WDATA;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_WSTRB;
wire    write_dataflow_1_U0_m_axi_gmem2_WLAST;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_WID;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_WUSER;
wire    write_dataflow_1_U0_m_axi_gmem2_ARVALID;
wire   [63:0] write_dataflow_1_U0_m_axi_gmem2_ARADDR;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_ARID;
wire   [31:0] write_dataflow_1_U0_m_axi_gmem2_ARLEN;
wire   [2:0] write_dataflow_1_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] write_dataflow_1_U0_m_axi_gmem2_ARBURST;
wire   [1:0] write_dataflow_1_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] write_dataflow_1_U0_m_axi_gmem2_ARPROT;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_ARQOS;
wire   [3:0] write_dataflow_1_U0_m_axi_gmem2_ARREGION;
wire   [0:0] write_dataflow_1_U0_m_axi_gmem2_ARUSER;
wire    write_dataflow_1_U0_m_axi_gmem2_RREADY;
wire    write_dataflow_1_U0_m_axi_gmem2_BREADY;
wire    write_dataflow_1_U0_write_stream_read;
wire    write_dataflow_1_U0_outFrame_read;
wire    write_dataflow_1_U0_elements_loc_read;
wire    ap_sync_continue;
wire    img_width_c_full_n;
wire   [31:0] img_width_c_dout;
wire    img_width_c_empty_n;
wire    elements_loc_c_full_n;
wire   [31:0] elements_loc_c_dout;
wire    elements_loc_c_empty_n;
wire    inFrame_c_full_n;
wire   [63:0] inFrame_c_dout;
wire    inFrame_c_empty_n;
wire    outFrame_c_full_n;
wire   [63:0] outFrame_c_dout;
wire    outFrame_c_empty_n;
wire    coefficient_c_full_n;
wire   [63:0] coefficient_c_dout;
wire    coefficient_c_empty_n;
wire    read_stream_full_n;
wire   [31:0] read_stream_dout;
wire    read_stream_empty_n;
wire    img_width_c9_full_n;
wire   [31:0] img_width_c9_dout;
wire    img_width_c9_empty_n;
wire    elements_loc_c10_full_n;
wire   [31:0] elements_loc_c10_dout;
wire    elements_loc_c10_empty_n;
wire    write_stream_full_n;
wire   [31:0] write_stream_dout;
wire    write_stream_empty_n;
wire    elements_loc_c11_full_n;
wire   [31:0] elements_loc_c11_dout;
wire    elements_loc_c11_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_split1_proc9_U0_ap_ready;
wire    ap_sync_Block_split1_proc9_U0_ap_ready;
reg   [1:0] Block_split1_proc9_U0_ap_ready_count;
reg    ap_sync_reg_read_dataflow_1_U0_ap_ready;
wire    ap_sync_read_dataflow_1_U0_ap_ready;
reg   [1:0] read_dataflow_1_U0_ap_ready_count;
reg    ap_sync_reg_compute_dataflow_1_U0_ap_ready;
wire    ap_sync_compute_dataflow_1_U0_ap_ready;
reg   [1:0] compute_dataflow_1_U0_ap_ready_count;
wire   [0:0] start_for_write_dataflow_1_U0_din;
wire    start_for_write_dataflow_1_U0_full_n;
wire   [0:0] start_for_write_dataflow_1_U0_dout;
wire    start_for_write_dataflow_1_U0_empty_n;
wire    read_dataflow_1_U0_start_full_n;
wire    read_dataflow_1_U0_start_write;
wire    compute_dataflow_1_U0_start_full_n;
wire    compute_dataflow_1_U0_start_write;
wire    write_dataflow_1_U0_start_full_n;
wire    write_dataflow_1_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_split1_proc9_U0_ap_ready = 1'b0;
#0 Block_split1_proc9_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_read_dataflow_1_U0_ap_ready = 1'b0;
#0 read_dataflow_1_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_compute_dataflow_1_U0_ap_ready = 1'b0;
#0 compute_dataflow_1_U0_ap_ready_count = 2'd0;
end

convolve_fpga_gmem1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(read_dataflow_1_U0_m_axi_gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(read_dataflow_1_U0_m_axi_gmem1_ARADDR),
    .I_ARID(read_dataflow_1_U0_m_axi_gmem1_ARID),
    .I_ARLEN(read_dataflow_1_U0_m_axi_gmem1_ARLEN),
    .I_ARSIZE(read_dataflow_1_U0_m_axi_gmem1_ARSIZE),
    .I_ARLOCK(read_dataflow_1_U0_m_axi_gmem1_ARLOCK),
    .I_ARCACHE(read_dataflow_1_U0_m_axi_gmem1_ARCACHE),
    .I_ARQOS(read_dataflow_1_U0_m_axi_gmem1_ARQOS),
    .I_ARPROT(read_dataflow_1_U0_m_axi_gmem1_ARPROT),
    .I_ARUSER(read_dataflow_1_U0_m_axi_gmem1_ARUSER),
    .I_ARBURST(read_dataflow_1_U0_m_axi_gmem1_ARBURST),
    .I_ARREGION(read_dataflow_1_U0_m_axi_gmem1_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(read_dataflow_1_U0_m_axi_gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

convolve_fpga_gmem2_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(gmem2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(gmem2_RDATA),
    .I_RID(gmem2_RID),
    .I_RUSER(gmem2_RUSER),
    .I_RRESP(gmem2_RRESP),
    .I_RLAST(gmem2_RLAST),
    .I_AWVALID(write_dataflow_1_U0_m_axi_gmem2_AWVALID),
    .I_AWREADY(gmem2_AWREADY),
    .I_AWADDR(write_dataflow_1_U0_m_axi_gmem2_AWADDR),
    .I_AWID(write_dataflow_1_U0_m_axi_gmem2_AWID),
    .I_AWLEN(write_dataflow_1_U0_m_axi_gmem2_AWLEN),
    .I_AWSIZE(write_dataflow_1_U0_m_axi_gmem2_AWSIZE),
    .I_AWLOCK(write_dataflow_1_U0_m_axi_gmem2_AWLOCK),
    .I_AWCACHE(write_dataflow_1_U0_m_axi_gmem2_AWCACHE),
    .I_AWQOS(write_dataflow_1_U0_m_axi_gmem2_AWQOS),
    .I_AWPROT(write_dataflow_1_U0_m_axi_gmem2_AWPROT),
    .I_AWUSER(write_dataflow_1_U0_m_axi_gmem2_AWUSER),
    .I_AWBURST(write_dataflow_1_U0_m_axi_gmem2_AWBURST),
    .I_AWREGION(write_dataflow_1_U0_m_axi_gmem2_AWREGION),
    .I_WVALID(write_dataflow_1_U0_m_axi_gmem2_WVALID),
    .I_WREADY(gmem2_WREADY),
    .I_WDATA(write_dataflow_1_U0_m_axi_gmem2_WDATA),
    .I_WID(write_dataflow_1_U0_m_axi_gmem2_WID),
    .I_WUSER(write_dataflow_1_U0_m_axi_gmem2_WUSER),
    .I_WLAST(write_dataflow_1_U0_m_axi_gmem2_WLAST),
    .I_WSTRB(write_dataflow_1_U0_m_axi_gmem2_WSTRB),
    .I_BVALID(gmem2_BVALID),
    .I_BREADY(write_dataflow_1_U0_m_axi_gmem2_BREADY),
    .I_BRESP(gmem2_BRESP),
    .I_BID(gmem2_BID),
    .I_BUSER(gmem2_BUSER)
);

convolve_fpga_gmem3_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM3_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM3_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM3_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM3_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM3_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM3_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM3_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM3_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM3_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM3_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM3_CACHE_VALUE ))
gmem3_m_axi_U(
    .AWVALID(m_axi_gmem3_AWVALID),
    .AWREADY(m_axi_gmem3_AWREADY),
    .AWADDR(m_axi_gmem3_AWADDR),
    .AWID(m_axi_gmem3_AWID),
    .AWLEN(m_axi_gmem3_AWLEN),
    .AWSIZE(m_axi_gmem3_AWSIZE),
    .AWBURST(m_axi_gmem3_AWBURST),
    .AWLOCK(m_axi_gmem3_AWLOCK),
    .AWCACHE(m_axi_gmem3_AWCACHE),
    .AWPROT(m_axi_gmem3_AWPROT),
    .AWQOS(m_axi_gmem3_AWQOS),
    .AWREGION(m_axi_gmem3_AWREGION),
    .AWUSER(m_axi_gmem3_AWUSER),
    .WVALID(m_axi_gmem3_WVALID),
    .WREADY(m_axi_gmem3_WREADY),
    .WDATA(m_axi_gmem3_WDATA),
    .WSTRB(m_axi_gmem3_WSTRB),
    .WLAST(m_axi_gmem3_WLAST),
    .WID(m_axi_gmem3_WID),
    .WUSER(m_axi_gmem3_WUSER),
    .ARVALID(m_axi_gmem3_ARVALID),
    .ARREADY(m_axi_gmem3_ARREADY),
    .ARADDR(m_axi_gmem3_ARADDR),
    .ARID(m_axi_gmem3_ARID),
    .ARLEN(m_axi_gmem3_ARLEN),
    .ARSIZE(m_axi_gmem3_ARSIZE),
    .ARBURST(m_axi_gmem3_ARBURST),
    .ARLOCK(m_axi_gmem3_ARLOCK),
    .ARCACHE(m_axi_gmem3_ARCACHE),
    .ARPROT(m_axi_gmem3_ARPROT),
    .ARQOS(m_axi_gmem3_ARQOS),
    .ARREGION(m_axi_gmem3_ARREGION),
    .ARUSER(m_axi_gmem3_ARUSER),
    .RVALID(m_axi_gmem3_RVALID),
    .RREADY(m_axi_gmem3_RREADY),
    .RDATA(m_axi_gmem3_RDATA),
    .RLAST(m_axi_gmem3_RLAST),
    .RID(m_axi_gmem3_RID),
    .RUSER(m_axi_gmem3_RUSER),
    .RRESP(m_axi_gmem3_RRESP),
    .BVALID(m_axi_gmem3_BVALID),
    .BREADY(m_axi_gmem3_BREADY),
    .BRESP(m_axi_gmem3_BRESP),
    .BID(m_axi_gmem3_BID),
    .BUSER(m_axi_gmem3_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(compute_dataflow_1_U0_m_axi_gmem3_ARVALID),
    .I_ARREADY(gmem3_ARREADY),
    .I_ARADDR(compute_dataflow_1_U0_m_axi_gmem3_ARADDR),
    .I_ARID(compute_dataflow_1_U0_m_axi_gmem3_ARID),
    .I_ARLEN(compute_dataflow_1_U0_m_axi_gmem3_ARLEN),
    .I_ARSIZE(compute_dataflow_1_U0_m_axi_gmem3_ARSIZE),
    .I_ARLOCK(compute_dataflow_1_U0_m_axi_gmem3_ARLOCK),
    .I_ARCACHE(compute_dataflow_1_U0_m_axi_gmem3_ARCACHE),
    .I_ARQOS(compute_dataflow_1_U0_m_axi_gmem3_ARQOS),
    .I_ARPROT(compute_dataflow_1_U0_m_axi_gmem3_ARPROT),
    .I_ARUSER(compute_dataflow_1_U0_m_axi_gmem3_ARUSER),
    .I_ARBURST(compute_dataflow_1_U0_m_axi_gmem3_ARBURST),
    .I_ARREGION(compute_dataflow_1_U0_m_axi_gmem3_ARREGION),
    .I_RVALID(gmem3_RVALID),
    .I_RREADY(compute_dataflow_1_U0_m_axi_gmem3_RREADY),
    .I_RDATA(gmem3_RDATA),
    .I_RID(gmem3_RID),
    .I_RUSER(gmem3_RUSER),
    .I_RRESP(gmem3_RRESP),
    .I_RLAST(gmem3_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem3_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem3_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(gmem3_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem3_BRESP),
    .I_BID(gmem3_BID),
    .I_BUSER(gmem3_BUSER)
);

convolve_fpga_Block_split1_proc9 Block_split1_proc9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_split1_proc9_U0_ap_start),
    .start_full_n(start_for_write_dataflow_1_U0_full_n),
    .ap_done(Block_split1_proc9_U0_ap_done),
    .ap_continue(Block_split1_proc9_U0_ap_continue),
    .ap_idle(Block_split1_proc9_U0_ap_idle),
    .ap_ready(Block_split1_proc9_U0_ap_ready),
    .start_out(Block_split1_proc9_U0_start_out),
    .start_write(Block_split1_proc9_U0_start_write),
    .img_width(img_width),
    .img_height(img_height),
    .inFrame(inFrame),
    .outFrame(outFrame),
    .coefficient(coefficient),
    .img_width_out_din(Block_split1_proc9_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c_full_n),
    .img_width_out_write(Block_split1_proc9_U0_img_width_out_write),
    .elements_out_out_din(Block_split1_proc9_U0_elements_out_out_din),
    .elements_out_out_full_n(elements_loc_c_full_n),
    .elements_out_out_write(Block_split1_proc9_U0_elements_out_out_write),
    .inFrame_out_din(Block_split1_proc9_U0_inFrame_out_din),
    .inFrame_out_full_n(inFrame_c_full_n),
    .inFrame_out_write(Block_split1_proc9_U0_inFrame_out_write),
    .outFrame_out_din(Block_split1_proc9_U0_outFrame_out_din),
    .outFrame_out_full_n(outFrame_c_full_n),
    .outFrame_out_write(Block_split1_proc9_U0_outFrame_out_write),
    .coefficient_out_din(Block_split1_proc9_U0_coefficient_out_din),
    .coefficient_out_full_n(coefficient_c_full_n),
    .coefficient_out_write(Block_split1_proc9_U0_coefficient_out_write)
);

convolve_fpga_read_dataflow_1 read_dataflow_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_dataflow_1_U0_ap_start),
    .ap_done(read_dataflow_1_U0_ap_done),
    .ap_continue(read_dataflow_1_U0_ap_continue),
    .ap_idle(read_dataflow_1_U0_ap_idle),
    .ap_ready(read_dataflow_1_U0_ap_ready),
    .read_stream_din(read_dataflow_1_U0_read_stream_din),
    .read_stream_full_n(read_stream_full_n),
    .read_stream_write(read_dataflow_1_U0_read_stream_write),
    .m_axi_gmem1_AWVALID(read_dataflow_1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(read_dataflow_1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(read_dataflow_1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(read_dataflow_1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(read_dataflow_1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(read_dataflow_1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(read_dataflow_1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(read_dataflow_1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(read_dataflow_1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(read_dataflow_1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(read_dataflow_1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(read_dataflow_1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(read_dataflow_1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(read_dataflow_1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(read_dataflow_1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(read_dataflow_1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(read_dataflow_1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(read_dataflow_1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(read_dataflow_1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(read_dataflow_1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(read_dataflow_1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(read_dataflow_1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(read_dataflow_1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(read_dataflow_1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(read_dataflow_1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(read_dataflow_1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(read_dataflow_1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(read_dataflow_1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(read_dataflow_1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(read_dataflow_1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(read_dataflow_1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(read_dataflow_1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .inFrame_dout(inFrame_c_dout),
    .inFrame_empty_n(inFrame_c_empty_n),
    .inFrame_read(read_dataflow_1_U0_inFrame_read),
    .img_width_dout(img_width_c_dout),
    .img_width_empty_n(img_width_c_empty_n),
    .img_width_read(read_dataflow_1_U0_img_width_read),
    .elements_loc_dout(elements_loc_c_dout),
    .elements_loc_empty_n(elements_loc_c_empty_n),
    .elements_loc_read(read_dataflow_1_U0_elements_loc_read),
    .img_width_out_din(read_dataflow_1_U0_img_width_out_din),
    .img_width_out_full_n(img_width_c9_full_n),
    .img_width_out_write(read_dataflow_1_U0_img_width_out_write),
    .elements_loc_out_din(read_dataflow_1_U0_elements_loc_out_din),
    .elements_loc_out_full_n(elements_loc_c10_full_n),
    .elements_loc_out_write(read_dataflow_1_U0_elements_loc_out_write)
);

convolve_fpga_compute_dataflow_1 compute_dataflow_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_dataflow_1_U0_ap_start),
    .ap_done(compute_dataflow_1_U0_ap_done),
    .ap_continue(compute_dataflow_1_U0_ap_continue),
    .ap_idle(compute_dataflow_1_U0_ap_idle),
    .ap_ready(compute_dataflow_1_U0_ap_ready),
    .write_stream_din(compute_dataflow_1_U0_write_stream_din),
    .write_stream_full_n(write_stream_full_n),
    .write_stream_write(compute_dataflow_1_U0_write_stream_write),
    .read_stream_dout(read_stream_dout),
    .read_stream_empty_n(read_stream_empty_n),
    .read_stream_read(compute_dataflow_1_U0_read_stream_read),
    .m_axi_gmem3_AWVALID(compute_dataflow_1_U0_m_axi_gmem3_AWVALID),
    .m_axi_gmem3_AWREADY(1'b0),
    .m_axi_gmem3_AWADDR(compute_dataflow_1_U0_m_axi_gmem3_AWADDR),
    .m_axi_gmem3_AWID(compute_dataflow_1_U0_m_axi_gmem3_AWID),
    .m_axi_gmem3_AWLEN(compute_dataflow_1_U0_m_axi_gmem3_AWLEN),
    .m_axi_gmem3_AWSIZE(compute_dataflow_1_U0_m_axi_gmem3_AWSIZE),
    .m_axi_gmem3_AWBURST(compute_dataflow_1_U0_m_axi_gmem3_AWBURST),
    .m_axi_gmem3_AWLOCK(compute_dataflow_1_U0_m_axi_gmem3_AWLOCK),
    .m_axi_gmem3_AWCACHE(compute_dataflow_1_U0_m_axi_gmem3_AWCACHE),
    .m_axi_gmem3_AWPROT(compute_dataflow_1_U0_m_axi_gmem3_AWPROT),
    .m_axi_gmem3_AWQOS(compute_dataflow_1_U0_m_axi_gmem3_AWQOS),
    .m_axi_gmem3_AWREGION(compute_dataflow_1_U0_m_axi_gmem3_AWREGION),
    .m_axi_gmem3_AWUSER(compute_dataflow_1_U0_m_axi_gmem3_AWUSER),
    .m_axi_gmem3_WVALID(compute_dataflow_1_U0_m_axi_gmem3_WVALID),
    .m_axi_gmem3_WREADY(1'b0),
    .m_axi_gmem3_WDATA(compute_dataflow_1_U0_m_axi_gmem3_WDATA),
    .m_axi_gmem3_WSTRB(compute_dataflow_1_U0_m_axi_gmem3_WSTRB),
    .m_axi_gmem3_WLAST(compute_dataflow_1_U0_m_axi_gmem3_WLAST),
    .m_axi_gmem3_WID(compute_dataflow_1_U0_m_axi_gmem3_WID),
    .m_axi_gmem3_WUSER(compute_dataflow_1_U0_m_axi_gmem3_WUSER),
    .m_axi_gmem3_ARVALID(compute_dataflow_1_U0_m_axi_gmem3_ARVALID),
    .m_axi_gmem3_ARREADY(gmem3_ARREADY),
    .m_axi_gmem3_ARADDR(compute_dataflow_1_U0_m_axi_gmem3_ARADDR),
    .m_axi_gmem3_ARID(compute_dataflow_1_U0_m_axi_gmem3_ARID),
    .m_axi_gmem3_ARLEN(compute_dataflow_1_U0_m_axi_gmem3_ARLEN),
    .m_axi_gmem3_ARSIZE(compute_dataflow_1_U0_m_axi_gmem3_ARSIZE),
    .m_axi_gmem3_ARBURST(compute_dataflow_1_U0_m_axi_gmem3_ARBURST),
    .m_axi_gmem3_ARLOCK(compute_dataflow_1_U0_m_axi_gmem3_ARLOCK),
    .m_axi_gmem3_ARCACHE(compute_dataflow_1_U0_m_axi_gmem3_ARCACHE),
    .m_axi_gmem3_ARPROT(compute_dataflow_1_U0_m_axi_gmem3_ARPROT),
    .m_axi_gmem3_ARQOS(compute_dataflow_1_U0_m_axi_gmem3_ARQOS),
    .m_axi_gmem3_ARREGION(compute_dataflow_1_U0_m_axi_gmem3_ARREGION),
    .m_axi_gmem3_ARUSER(compute_dataflow_1_U0_m_axi_gmem3_ARUSER),
    .m_axi_gmem3_RVALID(gmem3_RVALID),
    .m_axi_gmem3_RREADY(compute_dataflow_1_U0_m_axi_gmem3_RREADY),
    .m_axi_gmem3_RDATA(gmem3_RDATA),
    .m_axi_gmem3_RLAST(gmem3_RLAST),
    .m_axi_gmem3_RID(gmem3_RID),
    .m_axi_gmem3_RUSER(gmem3_RUSER),
    .m_axi_gmem3_RRESP(gmem3_RRESP),
    .m_axi_gmem3_BVALID(1'b0),
    .m_axi_gmem3_BREADY(compute_dataflow_1_U0_m_axi_gmem3_BREADY),
    .m_axi_gmem3_BRESP(2'd0),
    .m_axi_gmem3_BID(1'd0),
    .m_axi_gmem3_BUSER(1'd0),
    .coefficient_dout(coefficient_c_dout),
    .coefficient_empty_n(coefficient_c_empty_n),
    .coefficient_read(compute_dataflow_1_U0_coefficient_read),
    .img_width_dout(img_width_c9_dout),
    .img_width_empty_n(img_width_c9_empty_n),
    .img_width_read(compute_dataflow_1_U0_img_width_read),
    .elements_loc_dout(elements_loc_c10_dout),
    .elements_loc_empty_n(elements_loc_c10_empty_n),
    .elements_loc_read(compute_dataflow_1_U0_elements_loc_read),
    .elements_loc_out_din(compute_dataflow_1_U0_elements_loc_out_din),
    .elements_loc_out_full_n(elements_loc_c11_full_n),
    .elements_loc_out_write(compute_dataflow_1_U0_elements_loc_out_write)
);

convolve_fpga_write_dataflow_1 write_dataflow_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_dataflow_1_U0_ap_start),
    .ap_done(write_dataflow_1_U0_ap_done),
    .ap_continue(write_dataflow_1_U0_ap_continue),
    .ap_idle(write_dataflow_1_U0_ap_idle),
    .ap_ready(write_dataflow_1_U0_ap_ready),
    .m_axi_gmem2_AWVALID(write_dataflow_1_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(write_dataflow_1_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(write_dataflow_1_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(write_dataflow_1_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(write_dataflow_1_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(write_dataflow_1_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(write_dataflow_1_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(write_dataflow_1_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(write_dataflow_1_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(write_dataflow_1_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(write_dataflow_1_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(write_dataflow_1_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(write_dataflow_1_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(gmem2_WREADY),
    .m_axi_gmem2_WDATA(write_dataflow_1_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(write_dataflow_1_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(write_dataflow_1_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(write_dataflow_1_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(write_dataflow_1_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(write_dataflow_1_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(write_dataflow_1_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(write_dataflow_1_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(write_dataflow_1_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(write_dataflow_1_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(write_dataflow_1_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(write_dataflow_1_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(write_dataflow_1_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(write_dataflow_1_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(write_dataflow_1_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(write_dataflow_1_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(write_dataflow_1_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(write_dataflow_1_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(32'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(gmem2_BVALID),
    .m_axi_gmem2_BREADY(write_dataflow_1_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(gmem2_BRESP),
    .m_axi_gmem2_BID(gmem2_BID),
    .m_axi_gmem2_BUSER(gmem2_BUSER),
    .write_stream_dout(write_stream_dout),
    .write_stream_empty_n(write_stream_empty_n),
    .write_stream_read(write_dataflow_1_U0_write_stream_read),
    .outFrame_dout(outFrame_c_dout),
    .outFrame_empty_n(outFrame_c_empty_n),
    .outFrame_read(write_dataflow_1_U0_outFrame_read),
    .elements_loc_dout(elements_loc_c11_dout),
    .elements_loc_empty_n(elements_loc_c11_empty_n),
    .elements_loc_read(write_dataflow_1_U0_elements_loc_read)
);

convolve_fpga_fifo_w32_d2_S img_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc9_U0_img_width_out_din),
    .if_full_n(img_width_c_full_n),
    .if_write(Block_split1_proc9_U0_img_width_out_write),
    .if_dout(img_width_c_dout),
    .if_empty_n(img_width_c_empty_n),
    .if_read(read_dataflow_1_U0_img_width_read)
);

convolve_fpga_fifo_w32_d2_S elements_loc_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc9_U0_elements_out_out_din),
    .if_full_n(elements_loc_c_full_n),
    .if_write(Block_split1_proc9_U0_elements_out_out_write),
    .if_dout(elements_loc_c_dout),
    .if_empty_n(elements_loc_c_empty_n),
    .if_read(read_dataflow_1_U0_elements_loc_read)
);

convolve_fpga_fifo_w64_d2_S inFrame_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc9_U0_inFrame_out_din),
    .if_full_n(inFrame_c_full_n),
    .if_write(Block_split1_proc9_U0_inFrame_out_write),
    .if_dout(inFrame_c_dout),
    .if_empty_n(inFrame_c_empty_n),
    .if_read(read_dataflow_1_U0_inFrame_read)
);

convolve_fpga_fifo_w64_d4_S outFrame_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc9_U0_outFrame_out_din),
    .if_full_n(outFrame_c_full_n),
    .if_write(Block_split1_proc9_U0_outFrame_out_write),
    .if_dout(outFrame_c_dout),
    .if_empty_n(outFrame_c_empty_n),
    .if_read(write_dataflow_1_U0_outFrame_read)
);

convolve_fpga_fifo_w64_d3_S coefficient_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_split1_proc9_U0_coefficient_out_din),
    .if_full_n(coefficient_c_full_n),
    .if_write(Block_split1_proc9_U0_coefficient_out_write),
    .if_dout(coefficient_c_dout),
    .if_empty_n(coefficient_c_empty_n),
    .if_read(compute_dataflow_1_U0_coefficient_read)
);

convolve_fpga_fifo_w32_d2_S read_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_dataflow_1_U0_read_stream_din),
    .if_full_n(read_stream_full_n),
    .if_write(read_dataflow_1_U0_read_stream_write),
    .if_dout(read_stream_dout),
    .if_empty_n(read_stream_empty_n),
    .if_read(compute_dataflow_1_U0_read_stream_read)
);

convolve_fpga_fifo_w32_d2_S img_width_c9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_dataflow_1_U0_img_width_out_din),
    .if_full_n(img_width_c9_full_n),
    .if_write(read_dataflow_1_U0_img_width_out_write),
    .if_dout(img_width_c9_dout),
    .if_empty_n(img_width_c9_empty_n),
    .if_read(compute_dataflow_1_U0_img_width_read)
);

convolve_fpga_fifo_w32_d2_S elements_loc_c10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_dataflow_1_U0_elements_loc_out_din),
    .if_full_n(elements_loc_c10_full_n),
    .if_write(read_dataflow_1_U0_elements_loc_out_write),
    .if_dout(elements_loc_c10_dout),
    .if_empty_n(elements_loc_c10_empty_n),
    .if_read(compute_dataflow_1_U0_elements_loc_read)
);

convolve_fpga_fifo_w32_d2_S write_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_dataflow_1_U0_write_stream_din),
    .if_full_n(write_stream_full_n),
    .if_write(compute_dataflow_1_U0_write_stream_write),
    .if_dout(write_stream_dout),
    .if_empty_n(write_stream_empty_n),
    .if_read(write_dataflow_1_U0_write_stream_read)
);

convolve_fpga_fifo_w32_d2_S elements_loc_c11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_dataflow_1_U0_elements_loc_out_din),
    .if_full_n(elements_loc_c11_full_n),
    .if_write(compute_dataflow_1_U0_elements_loc_out_write),
    .if_dout(elements_loc_c11_dout),
    .if_empty_n(elements_loc_c11_empty_n),
    .if_read(write_dataflow_1_U0_elements_loc_read)
);

convolve_fpga_start_for_write_dataflow_1_U0 start_for_write_dataflow_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_dataflow_1_U0_din),
    .if_full_n(start_for_write_dataflow_1_U0_full_n),
    .if_write(Block_split1_proc9_U0_start_write),
    .if_dout(start_for_write_dataflow_1_U0_dout),
    .if_empty_n(start_for_write_dataflow_1_U0_empty_n),
    .if_read(write_dataflow_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_split1_proc9_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_split1_proc9_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_split1_proc9_U0_ap_ready <= ap_sync_Block_split1_proc9_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_compute_dataflow_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_compute_dataflow_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_compute_dataflow_1_U0_ap_ready <= ap_sync_compute_dataflow_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_dataflow_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_dataflow_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_dataflow_1_U0_ap_ready <= ap_sync_read_dataflow_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_split1_proc9_U0_ap_ready))) begin
        Block_split1_proc9_U0_ap_ready_count <= (Block_split1_proc9_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_split1_proc9_U0_ap_ready))) begin
        Block_split1_proc9_U0_ap_ready_count <= (Block_split1_proc9_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (compute_dataflow_1_U0_ap_ready == 1'b0))) begin
        compute_dataflow_1_U0_ap_ready_count <= (compute_dataflow_1_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (compute_dataflow_1_U0_ap_ready == 1'b1))) begin
        compute_dataflow_1_U0_ap_ready_count <= (compute_dataflow_1_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (read_dataflow_1_U0_ap_ready == 1'b0))) begin
        read_dataflow_1_U0_ap_ready_count <= (read_dataflow_1_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (read_dataflow_1_U0_ap_ready == 1'b1))) begin
        read_dataflow_1_U0_ap_ready_count <= (read_dataflow_1_U0_ap_ready_count + 2'd1);
    end
end

assign Block_split1_proc9_U0_ap_continue = 1'b1;

assign Block_split1_proc9_U0_ap_start = ((ap_sync_reg_Block_split1_proc9_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_done = write_dataflow_1_U0_ap_done;

assign ap_idle = (write_dataflow_1_U0_ap_idle & read_dataflow_1_U0_ap_idle & compute_dataflow_1_U0_ap_idle & Block_split1_proc9_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_split1_proc9_U0_ap_ready = (ap_sync_reg_Block_split1_proc9_U0_ap_ready | Block_split1_proc9_U0_ap_ready);

assign ap_sync_compute_dataflow_1_U0_ap_ready = (compute_dataflow_1_U0_ap_ready | ap_sync_reg_compute_dataflow_1_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = write_dataflow_1_U0_ap_done;

assign ap_sync_read_dataflow_1_U0_ap_ready = (read_dataflow_1_U0_ap_ready | ap_sync_reg_read_dataflow_1_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_dataflow_1_U0_ap_ready & ap_sync_compute_dataflow_1_U0_ap_ready & ap_sync_Block_split1_proc9_U0_ap_ready);

assign compute_dataflow_1_U0_ap_continue = 1'b1;

assign compute_dataflow_1_U0_ap_start = ((ap_sync_reg_compute_dataflow_1_U0_ap_ready ^ 1'b1) & ap_start);

assign compute_dataflow_1_U0_start_full_n = 1'b1;

assign compute_dataflow_1_U0_start_write = 1'b0;

assign read_dataflow_1_U0_ap_continue = 1'b1;

assign read_dataflow_1_U0_ap_start = ((ap_sync_reg_read_dataflow_1_U0_ap_ready ^ 1'b1) & ap_start);

assign read_dataflow_1_U0_start_full_n = 1'b1;

assign read_dataflow_1_U0_start_write = 1'b0;

assign start_for_write_dataflow_1_U0_din = 1'b1;

assign write_dataflow_1_U0_ap_continue = 1'b1;

assign write_dataflow_1_U0_ap_start = start_for_write_dataflow_1_U0_empty_n;

assign write_dataflow_1_U0_start_full_n = 1'b1;

assign write_dataflow_1_U0_start_write = 1'b0;

endmodule //convolve_fpga
